error: my error messsage source=unknown
warn: my warning messsage source=unknown
info: my info messsage source=unknown
trace: my trace messsage source=unknown
tracefiner: my tracefiner messsage source=unknown
tracefinest: my tracefinest messsage source=unknown
error: my error messsage source=source1
warn: my warning messsage source=source1
info: my info messsage source=source1
trace: my trace messsage source=source1
tracefiner: my tracefiner messsage source=source1
tracefinest: my tracefinest messsage source=source1
error: my error messsage source=unknown
warn: my warning messsage source=unknown
info: my info messsage source=unknown
error: my error messsage source=source1
warn: my warning messsage source=source1
info: my info messsage source=source1
error: uncaughtException: unknowhFunction is not defined date=Wed Apr 01 2015 08:50:11 GMT-0400 (Eastern Daylight Time), pid=69484, uid=null, gid=null, cwd=C:\01-src\gitorious\ti_logger\test, execPath=C:\Program Files (x86)\nodejs\node.exe, version=v0.10.33, argv=[node, C:\01-src\gitorious\ti_logger\test\test2.js], rss=14761984, heapTotal=7130752, heapUsed=3095960, loadavg=[0, 0, 0], uptime=2308997.1339645
ReferenceError: unknowhFunction is not defined
,    at throwAnException (C:\01-src\gitorious\ti_logger\test\test2.js:93:3)
,    at fillLog (C:\01-src\gitorious\ti_logger\test\test2.js:83:2)
,    at Object.<anonymous> (C:\01-src\gitorious\ti_logger\test\test2.js:89:1)
,    at Module._compile (module.js:456:26)
,    at Object.Module._extensions..js (module.js:474:10)
,    at Module.load (module.js:356:32)
,    at Function.Module._load (module.js:312:12)
,    at Function.Module.runMain (module.js:497:10)
,    at startup (node.js:119:16)
,    at node.js:906:3

